version: "3.5"

services:
  uptime:
    image: louislam/uptime-kuma:1
    volumes:
      - uptime-data:/app/data
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.10'
          memory: 64M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik
        # https config
        - traefik.http.routers.uptime-https.rule=Host(`uptime.opensuse.net.br`) || Host(`status.opensuse.net.br`)
        - traefik.http.routers.uptime-https.entrypoints=https
        - traefik.http.routers.uptime-https.tls=true
        - traefik.http.routers.uptime-https.tls.certresolver=letsencrypt
        - traefik.http.routers.uptime-https.service=uptime
        # http config
        - traefik.http.routers.uptime-http.rule=Host(`uptime.opensuse.net.br`) || Host(`status.opensuse.net.br`)
        - traefik.http.routers.uptime-http.entrypoints=http
        - traefik.http.routers.uptime-http.service=uptime
        # service config
        - traefik.http.services.uptime.loadbalancer.server.port=3001

networks:
  traefik:
    external: true

volumes:
  uptime-data:
    external: true
